---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/loans/simulation_batches":
    post:
      summary: Create a Simulation Batch
      tags:
      - Simulation Batches
      parameters: []
      responses:
        '200':
          description: Simulation batch created successfully (sync)
        '422':
          description: Invalid request (missing data)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                simulation_batch:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      example: user@example.com
                    sync:
                      type: boolean
                      example: true
                    simulations_data:
                      type: array
                      items:
                        type: object
                        properties:
                          loan_amount:
                            type: number
                            example: 10000
                          birth_date:
                            type: string
                            format: date
                            example: '2005-06-08'
                          term_in_months:
                            type: integer
                            example: 12
                        required:
                        - loan_amount
                        - birth_date
                        - term_in_months
                  example:
                    email: user@example.com
                    sync: false
                    simulations_data:
                    - loan_amount: 10000
                      birth_date: '2005-06-08'
                      term_in_months: 12
                    - loan_amount: 10000
                      birth_date: '2005-06-08'
                      term_in_months: 24
                    - loan_amount: 10000
                      birth_date: '2005-06-08'
                      term_in_months: 48
                    - loan_amount: 10000
                      birth_date: '2005-06-08'
                      term_in_months: 60
                  required:
                  - simulations_data
              required:
              - simulation_batch
  "/api/v1/loans/simulations":
    post:
      summary: Simulate a loan
      tags:
      - Loans
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity - missing birth_date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loan_amount:
                  type: integer
                birth_date:
                  type: string
                  format: date
                term_in_months:
                  type: integer
              example:
                loan_amount: 10000
                birth_date: '2005-06-08'
                term_in_months: 24
              required:
              - loan_amount
              - birth_date
              - term_in_months
servers:
- url: http://localhost:3000
